[all:vars]
ansible_user=root
ansible_become=true

[control_plane]
master-node ansible_host=159.223.86.139

[workers]
worker-node-1 ansible_host=143.198.202.28
; worker-node-2 ansible_host=178.128.82.157

[k8s_cluster:children]
control_plane
workers

[proxy_servers]
proxy-node-1 ansible_host=68.183.224.199
# Add more nodes here if needed