[all:vars]
ansible_user=root
ansible_become=true

[control_plane]
master-node ansible_host=168.144.128.68

[workers]
worker-node-1 ansible_host=157.245.55.237
; worker-node-2 ansible_host=178.128.82.157

[k8s_cluster:children]
control_plane
workers

[proxy_servers]
proxy-node-1 ansible_host=188.166.218.123
# Add more nodes here if needed