---
# ==============================================================================
# SECURITY GUARDRAILS ENTRYPOINT
# ==============================================================================

- name: Include Istio Security Guardrails
  ansible.builtin.include_tasks: istio.yml
  when: mesh_type == "istio"
  tags:
    - security
    - guardrails

- name: Include Kuma Security Guardrails
  ansible.builtin.include_tasks: kuma.yml
  when: mesh_type == "kuma"
  tags:
    - security
    - guardrails
