apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: argo-gateway
  namespace: "{{ argo_namespace }}"
spec:
  selector:
    istio: eastwestgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "{{ argo_cd_server_host }}"
